INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Clarence', 'Ho', '1980-07-30');
INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Scott', 'Tiger', '1990-11-02');
INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('John', 'Smith', '1964-02-28');
INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Peter', 'Jacson', '1944-01-10');
INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Jacky', 'Chan', '1955-10-31');
INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Susan', 'Boyle', '1970-05-06');
INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Tinner', 'Turner', '1967-04-30');
INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Lotus', 'Notes', '1990-02-28');
INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Henry', 'Dickson', '1997-06-30');
INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Sam', 'Davis', '2001-01-31');
INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Max', 'Beckham', '2002-02-01');
INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Paul', 'Simon', '2002-02-28');